// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository_management_backend.Data;

#nullable disable

namespace Repository_management_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627101036_UserLoginLogoutStatus")]
    partial class UserLoginLogoutStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "merdekan",
                            IsActive = true,
                            Name = "Mərdəkan filialı"
                        },
                        new
                        {
                            Id = 2,
                            Code = "pirsagi",
                            IsActive = true,
                            Name = "Pirşağı filialı"
                        },
                        new
                        {
                            Id = 3,
                            Code = "baku",
                            IsActive = true,
                            Name = "Bakı Mərkəz filialı"
                        });
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Kind = "Standard",
                            Name = "Lesa",
                            Price = 50m,
                            RentType = "Monthly",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Kind = "Standard",
                            Name = "Təkərli lesa",
                            Price = 5m,
                            RentType = "Daily",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Kind = "Standard",
                            Name = "Dəmir dirək",
                            Price = 30m,
                            RentType = "Monthly",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 1,
                            Kind = "Standard",
                            Name = "Taxta",
                            Price = 10m,
                            RentType = "Monthly",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 1,
                            Kind = "Standard",
                            Name = "Vibrator",
                            Price = 8m,
                            RentType = "Daily",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            Kind = "Standard",
                            Name = "Lesa",
                            Price = 50m,
                            RentType = "Monthly",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 2,
                            Kind = "Standard",
                            Name = "Təkərli lesa",
                            Price = 5m,
                            RentType = "Daily",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 8,
                            BranchId = 2,
                            Kind = "Standard",
                            Name = "Dəmir dirək",
                            Price = 30m,
                            RentType = "Monthly",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 9,
                            BranchId = 2,
                            Kind = "Standard",
                            Name = "Taxta",
                            Price = 10m,
                            RentType = "Monthly",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 10,
                            BranchId = 2,
                            Kind = "Standard",
                            Name = "Vibrator",
                            Price = 8m,
                            RentType = "Daily",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 11,
                            BranchId = 3,
                            Kind = "Standard",
                            Name = "Lesa",
                            Price = 50m,
                            RentType = "Monthly",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 12,
                            BranchId = 3,
                            Kind = "Standard",
                            Name = "Təkərli lesa",
                            Price = 5m,
                            RentType = "Daily",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 13,
                            BranchId = 3,
                            Kind = "Standard",
                            Name = "Dəmir dirək",
                            Price = 30m,
                            RentType = "Monthly",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 14,
                            BranchId = 3,
                            Kind = "Standard",
                            Name = "Taxta",
                            Price = 10m,
                            RentType = "Monthly",
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 15,
                            BranchId = 3,
                            Kind = "Standard",
                            Name = "Vibrator",
                            Price = 8m,
                            RentType = "Daily",
                            Unit = "ədəd"
                        });
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "Phone");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Test Müştəri 1",
                            Phone = "+994 50 100 10 01"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Test Müştəri 2",
                            Phone = "+994 50 100 10 02"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Test Müştəri 3",
                            Phone = "+994 50 100 10 03"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Test Müştəri 4",
                            Phone = "+994 50 100 10 04"
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Test Müştəri 5",
                            Phone = "+994 50 100 10 05"
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Test Müştəri 6",
                            Phone = "+994 50 100 10 06"
                        });
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.CustomerLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DebtChange")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositChange")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Source")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("CustomerLedgerEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500m,
                            CustomerId = 1,
                            Date = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DebtChange = 300m,
                            DepositChange = 100m,
                            InvoiceId = 1,
                            Source = "invoice",
                            Type = "Mal götürüb (qaimə #0001)"
                        });
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.ExtensionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AddedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PaidNow")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("ExtensionHistories");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.InventoryStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("TotalCount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "Name")
                        .IsUnique();

                    b.ToTable("InventoryStocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Name = "Lesa",
                            TotalCount = 20m
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Name = "Taxta",
                            TotalCount = 100m
                        });
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExtraPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RemainingDebt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("BranchId", "InvoiceNo")
                        .IsUnique();

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            CustomerNameSnapshot = "Test Müştəri 1",
                            DepositAmount = 100m,
                            InvoiceDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceNo = "0001",
                            IsClosed = false,
                            PaidAmount = 200m,
                            Phone = "+994 50 100 10 01",
                            RemainingDebt = 300m,
                            ReturnDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalAmount = 500m,
                            UpdatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BoardCount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("CustomPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DailyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DayCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExtraBoardCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExtraBoardPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HeadCount")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFixedFee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReturnable")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("LesaExtraTaxtaCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("LesaExtraTaxtaPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LesaFreeTaxtaCount")
                        .HasColumnType("int");

                    b.Property<int?>("LesaHeadCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("LesaHeadPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LesaLongRodCount")
                        .HasColumnType("int");

                    b.Property<int?>("LesaShortRodCount")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PalesCount")
                        .HasColumnType("int");

                    b.Property<int?>("PoleCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RentMode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ReturnedQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RodCount")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VariantId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("VilkaCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Lesa",
                            CustomPrice = 50m,
                            InvoiceId = 1,
                            IsFixedFee = false,
                            IsRecurring = true,
                            IsReturnable = true,
                            Quantity = 5m,
                            ReturnedQuantity = 0m,
                            Subtotal = 250m,
                            Unit = "ədəd"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Taxta",
                            CustomPrice = 10m,
                            InvoiceId = 1,
                            IsFixedFee = false,
                            IsRecurring = true,
                            IsReturnable = true,
                            Quantity = 25m,
                            ReturnedQuantity = 0m,
                            Subtotal = 250m,
                            Unit = "ədəd"
                        });
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.ReturnHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("ReturnHistories");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogoutAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Category", b =>
                {
                    b.HasOne("Repository_management_backend.Models.Entities.Branch", "Branch")
                        .WithMany("Categories")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository_management_backend.Models.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Customer", b =>
                {
                    b.HasOne("Repository_management_backend.Models.Entities.Branch", "Branch")
                        .WithMany("Customers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.CustomerLedgerEntry", b =>
                {
                    b.HasOne("Repository_management_backend.Models.Entities.Customer", "Customer")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository_management_backend.Models.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.ExtensionHistory", b =>
                {
                    b.HasOne("Repository_management_backend.Models.Entities.Invoice", "Invoice")
                        .WithMany("ExtensionHistory")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.InventoryStock", b =>
                {
                    b.HasOne("Repository_management_backend.Models.Entities.Branch", "Branch")
                        .WithMany("InventoryStocks")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Invoice", b =>
                {
                    b.HasOne("Repository_management_backend.Models.Entities.Branch", "Branch")
                        .WithMany("Invoices")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository_management_backend.Models.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.InvoiceItem", b =>
                {
                    b.HasOne("Repository_management_backend.Models.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Payment", b =>
                {
                    b.HasOne("Repository_management_backend.Models.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.ReturnHistory", b =>
                {
                    b.HasOne("Repository_management_backend.Models.Entities.Invoice", "Invoice")
                        .WithMany("ReturnHistory")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.User", b =>
                {
                    b.HasOne("Repository_management_backend.Models.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Branch", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Customers");

                    b.Navigation("InventoryStocks");

                    b.Navigation("Invoices");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("Repository_management_backend.Models.Entities.Invoice", b =>
                {
                    b.Navigation("ExtensionHistory");

                    b.Navigation("Items");

                    b.Navigation("Payments");

                    b.Navigation("ReturnHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
